#!/usr/bin/env bash
# Prints number of occurrences of same IP address and HTTP status code of Apache HTTP request log
file_name="apache-access.log"
if test -f $file_name; then
  awk '{print $1,$9}' $file_name | sort | uniq -c | sort -gr
fi
